apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-synology
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume3/k8s-static-pv/grafana
    server: 10.1.0.3
