apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd 
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://charts.external-secrets.io
    targetRevision: 0.11.0
    chart: external-secrets
    helm:
      valuesObject:
            extendedMetricLabels: true
            serviceMonitor:
              enabled: true
            certManager:
              enabled: true
              cert:
                issuerRef:
                  name: letsencrypt-prod
                  kind: ClusterIssuer
                  group: cert-manager.io
  - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
    path: k8s/external-secrets-operator
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true