apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1p.svc.cluster.local:8080
      vaults:
        lab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token-lab
            key: token
            namespace: external-secrets