---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 4443
    - protocol: TCP
      name: admin
      port: 8080
  selector: # Select the pod container with app=treafik to communicate with CusrerIP inside the container
    app: traefik
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  #name: traefik-ingress-controller
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      name: traefik
      labels:
        app: traefik
    spec:
      hostNetwork: true # Using the host's network
      serviceAccountName: traefik-ingress-controller # Adjustment strategy
      terminationGracePeriodSeconds: 1
      containers:
        - name: traefik
          #name: traefik-ingress-lb
          image: traefik:v3.4
          args: # treafik does the domain certificate application here
            #- --configfile=/config/traefik.yaml
          ports: # Traefik/pod's 80 4443 8080 ports.
            - name: web
              containerPort: 80
              #hostPort: 80          # Bind the container port to port 80 of the server on which it resides
            - name: websecure
              containerPort: 443
              #hostPort: 443        # Bind the container port to port 443 of the host server.
            - name: admin
              containerPort: 8080 # Traefik Dashboard
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
