#
#  Author: Patrick LUZOLO
#  Date: 2025-05-22 13:47:33 +0000 (Tue, 22 May 2025)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/eldorplus/k8s-homelab
#  License: see accompanying Patrick LUZOLO LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/patrick-luzolo-eldorplus
#
# ============================================================================ #
#            H a s h i c o r p    V a u l t     K u s t o m i z a t i o n
# ============================================================================ #

---
replicaCount: 1

image:
  repository: quay.io/redhat-cop/vault-config-operator
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
env:
  - name: VAULT_ADDR
    value: http://vault-active.vault.svc.cluster.local:8200
  - name: VAULT_SKIP_VERIFY
    value: "true"
args: []
volumes: []
volumeMounts: []
podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 250Mi

nodeSelector: {}

tolerations: []

affinity: {}

kube_rbac_proxy:
  image:
    repository: quay.io/redhat-cop/kube-rbac-proxy
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

enableMonitoring: false
enableCertManager: true