apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
    path: k8s/node-feature-discovery
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
