apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd 
spec:
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://k8s-at-home.com/charts/
    targetRevision: 13.4.2
    chart: home-assistant
    helm:
      valueFiles:
      - $values/k8s/home-assistant/values.yaml
  - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
    # path: k8s/home-assistant/
    ref: values
    targetRevision: HEAD
  - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
    path: k8s/home-assistant/
    directory:
      recurse: true
    targetRevision: HEAD
  syncPolicy:
    # automated: {}
    syncOptions:
    - CreateNamespace=true