apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hass-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: "hass-secret"
        property: password