apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nr-snmp
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
    path: k8s/nr-snmp
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nr-snmp
  syncPolicy:
    automated:
      selfHeal: true
