apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrelic-snmp-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: newrelic
        property: credential