apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - prometheus/overlay
  - prometheus-stack/overlay
  - cert-manager/overlay
  - dashboard/overlay
  - ingress/traefik/overlay
  - vault/overlay
#  - device-plugins/overlay
#  - metrics-server/overlay
#  - kube-proxy/overlay
#  - kube-dns/overlay
#  - coredns/overlay
#  - kube-scheduler/overlay
#  - kube-controller-manager/overlay
#  - kube-apiserver/overlay