apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nas01.vfondevilla.com
    path: "/volume3/k8s-static-pv/mosquitto"
  storageClassName: manual