#
#  Author: Patrick LUZOLO
#  Date: 2025-05-22 13:47:33 +0000 (Tue, 22 May 2025)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/eldorplus/k8s-homelab
#  License: see accompanying Patrick LUZOLO LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/patrickluzolo/
#
# ============================================================================ #
#                     Traefik install on K3s via Helm Chart
# ============================================================================ #

# Disable bundled Traefik in K3s and deploy this to use an upgraded version

# Deploys custom Traefik via a Helm chart using the K3s Helm Controller:
#
#   https://docs.k3s.io/helm
#
#   https://github.com/k3s-io/helm-controller/

# XXX: do not call this file 'traefik.yaml' as if you've set k3s to '--disable traefik' it will remove it
#
# cp to /var/lib/rancher/k3s/server/manifests/traefil-helm.yaml

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: helm-charts  # deploy to a different namespace than the app for separation
spec:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 10.9.0
  targetNamespace: traefik
  set:
    global.systemDefaultRegistry: ""
  # or cp helm-chart-config.yaml /var/lib/rancher/k3s/server/manifests/
  valuesContent: |-
    experimental:
      http3:
        enabled: true
      plugins:
        enabled: true
    rollingUpdate:
      maxUnavailable: 0
    rbac:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
        http3: true
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"'
