apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-minio-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: velero-minio
      remoteRef:
        key: velero-minio
        property: password