apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-minio-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id = velero
          aws_secret_access_key = {{ .veleroMinioPassword }}
  data:
    - secretKey: veleroMinioPassword
      remoteRef:
        key: velero-minio
        property: password
