#
#  Author: Patrick LUZOLO
#  Date: 2021-11-29 16:14:02 +0000 (Mon, 29 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/eldorplus/k8s-homelab
#
#  License: see accompanying Patrick LUZOLO LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/patrick-luzolo-eldorplus
#
# ============================================================================ #
#                P r o m e t h e u s   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: prometheus  # Do not override helm chart, can cause issues

resources:
  - namespace.yaml

# done in namespace yaml now
#patchesStrategicMerge:
#  - goldilocks-namespace-enable.patch.yaml

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 15.18.0
    releaseName: prometheus
    namespace: prometheus
    includeCRDs: true
    valuesFile: values.yaml
