apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd 
spec:
  destination:
    namespace: z2m
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://charts.zigbee2mqtt.io
    targetRevision: 2.0.0
    chart: zigbee2mqtt
    helm:
      valuesObject:
        # customLabels:
        #   pod-security.kubernetes.io/enforce: privileged
        image:
          tag: 1.42.0
        statefulset:
          storage:
            enabled: true
            size: 2Gi
            existingVolume: zigbee2mqtt
            storageClassName: manual
          nodeSelector: 
            feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
        zigbee2mqtt:
          serial:
            port: /dev/ttyUSB0
            port: tcp://10.1.0.140:6638
          permit_join: true
          mqtt:
            server: "mqtt://mosquitto.mosquitto.svc.cluster.local"
  - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
    path: k8s/zigbee2mqtt
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true